runtime: java
env: flex
resources:
  memory_gb: 4
service: backend-test
runtime_config:
  jdk: openjdk8
handlers:
  - url: /.*
    script: this field is required, but ignored
manual_scaling:
  instances: 1